name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name:Arunvijay28
          outputs: |
            dist/github-snake.svg?color_snake=red&palette=github-dark
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=red&palette=github-dark&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
